swagger: '2.0'
info:
  title: Api from check racers and time with flasgger
  version: 1.0.0
  description: This swagger made by flasgger and flask
paths:
  /api/report:
    get:
      summary: Get all racers
      parameters:
        - name: format
          in: query
          description: format of the file
          required: true
          type: string
      responses:
        '200':
          description: All success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
            application/xml:
                schema:
                  type: array
                  items:
                    type: array
        '500':
          description: Error
  
  